### ISSUE TITLE
Clicking 'Home' from top right menu, abruptly goes white and then reloads all elements. Should be more elegant transition.

### ISSUE THREAD

**Issue by haayhappen** [haayhappen/Memento#12]

**Comment by Syr0kx** [comment]
sites fading in with "fade-in" class in animation.css
background of each file is black(color should be changed to some dark grey), so transition looks seamless

**Comment by haayhappen** [comment]
please also change bg color @Syr0kx , thanks

**Comment by haayhappen** [comment]
done
